# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ivcap < Formula
  desc ""
  homepage "https://github.com/reinventingscience/ivcap-cli"
  version "0.13.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reinventingscience/ivcap-cli/releases/download/v0.13.2/ivcap-cli_0.13.2_Darwin_arm64.tar.gz"
      sha256 "3adfc9aa66fb9f3cf7c4344eaf81122cacc00f7c0174301e0b2623a58f1708c7"

      def install
        bin.install "ivcap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reinventingscience/ivcap-cli/releases/download/v0.13.2/ivcap-cli_0.13.2_Darwin_x86_64.tar.gz"
      sha256 "aa977148bea43ca30bb5ae35ef0af54cf03a82af3c9c34c63d2da52145b9e9e5"

      def install
        bin.install "ivcap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reinventingscience/ivcap-cli/releases/download/v0.13.2/ivcap-cli_0.13.2_Linux_arm64.tar.gz"
      sha256 "383def2075756368a4721289e913f1229da4269e7ba0faa32490ed9501b881d4"

      def install
        bin.install "ivcap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reinventingscience/ivcap-cli/releases/download/v0.13.2/ivcap-cli_0.13.2_Linux_x86_64.tar.gz"
      sha256 "e4a14a1c7f171652b1b23e87c4fdc12fdb837fd9c2e558d8c9b5cd20d720bfe8"

      def install
        bin.install "ivcap"
      end
    end
  end
end
